# Site settings
title: Vincent
header-img: img/home-bg.jpg
email: 1@vincents.cn
description: "//"
baseurl: ""
url: "http://huanglins.github.io"
twitter_username: vincent
github_username:  huanglins
#facebook_username:  vincent
weibo_username: linxiaomu1995
zhihu_username: huang-lin-70-49

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
